### ISSUE TITLE
Border artifacts around list items at Windows 7

### ISSUE THREAD

**Issue by mlewand** [Komodo/Abyss-Skin#3]
Hi

There's a problem with list items in Abyss skin and Windows 7.

On mouse over it creates a annoying border (technically it seems to be shadow-box css property coming from generic Mozilla styling).

This artifact remains even if you move mouse out of element.

![Border Artifact](http://s3.postimg.org/vyywxlrdf/places_Artifact.png)

I don't know if it's a recent issue, because I'm migrating from Komodo 7.x, and I was using my own custom styles, that are no longer compatibile with new Komodo so I want to reuse ActiveState theme.

## Similar Case

I've faced similar case eg. in Preferences / Key Bindings. Each list entry has a similar border.

![Key Bindings screen](http://s2.postimg.org/kasd8rlax/key_Bindings.png)

Solution was to set following CSS code:

```css
listitem {
    box-shadow: none !important;
}
```

## My Initial Bets

I've tried to hack this thing on my own, but with no luck. I've tried code like this:

```css
treechildren:hover::-moz-tree-cell {
	box-shadow: none !important;
}
```

I have no idea how to fix it, most likely because I don't Mozilla XUL stuff :).
